### ISSUE TITLE
Sept 23 - Take the Boring out of Forms with Vue and Azure Static Web Apps

### ISSUE THREAD

**Issue by mebaumb** [microsoft/Reactors#155]
# Event Information
| Category | Details |
|-----------|---------|
| Reactor Topic | Cloud Development |
| Monthly Topic (if applicable) | <Topic taken from [Azure Dev Marketing](https://aka.ms/DevEdCalFY21H1)> |
| Weekly Topic (if applicable) | <Topic decided by RCT if relevant> |
| Stream Topic | <2-5 words describing the topic> |
| Stream Date | September 23, 2020 | 
| Stream Time | 9:00 am PST | 
| Stream Duration | 60 mins | 
| Title |Take the Boring out of Forms with Vue and Azure Static Web Apps|
| Description |99% of the applications written consist of a form on top of a database. But you never see those kinds of apps in demos for new technology. Why? Because people think they are boring! In truth, they are a quick, easy way to create forms. In this stream, we'll build a data entry form using the Vue framework, store the data in a Cosmos DB, and deploy it to Azure Static Web Apps.|
| Speaker | Burke Holland |
| Moderator | TBD |
| SharePoint ID | 7872 |  

Additional Resources:  
<Additional resources that can be linked from social media for promotion or added to the description of VOD>

# Event Checklist

## 10 Weeks Prior
- [ ] Reactor Content Team (RCT) or Speaker opens a new issue for an upcoming stream filling in the Event Information table. Both RCT and Speaker are marked as assignees.
- [ ] RCT and Speaker discuss details of the event in the comments of this issue. RCT adds a _confirmed-event_ label and either _global-twitch-event_ or _local-teams-event_ tag to the issue and adds event to the __Global Live Streams__ project or the __Local Live Streams__ project. Issue will appear in the __Upcoming Streams__ column

## 8 Weeks Prior
- [ ] RCT does a review of title and description
- [ ] RCT moves the issue to the __Ready for Marketing__ column
- [ ] RCT informs the Reactor Marketing Team of the new event information
- [ ] RCT provides speaker with assets (e.g. slides, overlays) and the survey data for the event
- [ ] RCT moves the issue to the __Stream Preparation In Progress__ column

## 2 Weeks Prior
- [ ] Speaker opens a PR with the new content for the stream, adds it to the same project chosen above, and adds the _content-development_ and either _global-twitch-event_ or _local-teams-event_ tag to the PR. PR will appear in the __Stream Preparation In Progress__ column. 
- [ ] Speaker adds to the same PR a modification to the [Streaming README](https://github.com/microsoft/Reactors/tree/master/Online) 
- [ ] Speaker adds the RCT assigned to the issue as the reviewer when it is ready for review/merge
- [ ] RCT reviews, approves, and merges the changes and the PR moves to the __Stream Complete__ column

## 1 Week Prior
- [ ] Speaker and Moderator test setup for streaming (instructions coming soon)
- [ ] RCT checks in with the speaker and moves the issue to the __Ready to Stream__ column

## During and After Stream
- [ ] Speaker and Moderator run the stream
- [ ] RCT submits recording to be uploaded to the Reactor YouTube and to be made available on LearnTV
- [ ] RCT moves issue to the __Stream Complete__ column

**Comment by KimberlyBolton1** [comment]
Edited title/abstract and sent to speaker to review.

**Comment by KimberlyBolton1** [comment]
Slight reword of description after feedback from content owner. Good to go.

**Comment by sguthals** [comment]
Moved to another repo.
