### ISSUE TITLE
Problems today 2/18 working with 'az hack create... '

### ISSUE THREAD

**Issue by daniel-dc-cd** [microsoft/Reactors#47]
az hack create --name reactor --runtime python --location northcentralus --ai --output yaml

It appears that version 2.0.81 has some problems and no one in my workshop today could get the above command to complete. The error was something I've seen on the azure cli github repo issues.
"Unable to get API version for type 'None' in profile 'latest'
Traceback (most recent call last): ... " 

**Workaround:**
If you downgrade the cli to 2.0.79 things work fine. People having problems can uninstall the az cli using brew or pip or chocolatey and then reinstall with pip or choco with the version flag...

**Comment by meaghanlewis** [comment]
Thanks for sharing this feedback @daniel-dc-cd!  We'll look into this issue further, and in the meantime, can share the workaround you provided for upcoming AI workshops.

**Comment by meaghanlewis** [comment]
@daniel-dc-cd just wanted to update you and let you know that the **az hack extension** is back up and running as expected. 

It looks like the CLI team made a breaking change, and the extension code needed to be updated as a result. In the future, we are hoping to get a better idea of their release cadence so we can proactively anticipate and make changes on our end.
 
I'll go ahead and close this issue out, but we can open another for any new problems experienced.
